package:
  name: phenix-deps
  version: 2019.09.01                   # YYYY.MM.DD

requirements:
  run:
    - cctbx-deps
    - amber_phenix
    - onedep_api

    # dials
    - jinja2
    - msgpack-c
    - msgpack-python
    - orderedset
    - procrunner
    - python-blosc
    - scikit-learn
    - scipy
    - tqdm =4.23.4

    # dials-data
    - pyyaml

    # xia2
    - tabulate

    # Phenix
    - send2trash
    - PyRTF

about:
  home: https://github.com/phenix-project/phenix_dependencies
  summary: Metapackage for Phenix dependencies
  description: "This is a metapackage that just installs the dependencies for \
    Phenix. The conda-forge and cctbx channels are required."
  doc_url: https://phenix-online.org/documentation
  dev_url: https://phenix-online.org

extra:
  recipe-maintainers:
    - bkpoon
